spring:
  datasource:
    url: jdbc:mysql://localhost:3333/agency
    username: root
    password: Root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8999
  servlet:
    context-path: /agency
  error:
    whitelabel:
      enabled: false